### ISSUE TITLE
share injector between 2 apps

### ISSUE THREAD

**Issue by anzolo** [jpex-js/vue-inject#12]
Hello!
i have app with 2 parts. First use Vue, but second use another framework.
vue-inject work perfect in Vue-part.
but when I try to use the component in another part, it doesn't work.

init vue-inject:

```
import Vue from 'vue'
import injector from 'vue-inject';

import DB from './db.js'

injector.service('db', DB);

Vue.use(injector);

export default injector;
```

that`s i try get service in another part of app:

```
getLayerByRef(ref) {        
        let db = injector.get('db');
        if (db.is_ref(ref)) {
          ...
        }
}
```
in runtime i have:

`db = {}`

can throw me ideas, what's wrong?

**Comment by jackmellis** [comment]
That's strange. Are you sure that the injector you import in the second example is definitely the same object as the one in the first? It might help to get a bit more context.

**Comment by anzolo** [comment]
Thanx for response.
It`s my fault :)
vue-inject work like a charm
