### ISSUE TITLE
Add option to make all dependencies optional

### ISSUE THREAD

**Issue by downace** [jpex-js/vue-inject#13]
It can be useful for unit testing. Each test is concentrated on one piece of functionality and registering EVERY component dependency for EVERY test is a little bit annoying:
```javascript
describe('tests with first dependency', () => {
  injector.constant('firstDep', firstDep);
  injector.constant('secondDep', secondDepMock); // Actually not used during this test
  injector.constant('thirdDep', thirdDepMock); // Not used too

  ...

});

describe('tests with second dependency', () => {
  // Same thing here...
  injector.constant('firstDep', firstDepMock);
  injector.constant('secondDep', secondDep);
  injector.constant('thirdDep', thirdDepMock);

  ...

});

...
```
It would be great to do something like this:
```javascript
// This enables wrapping every dependency in underscores before resolving
injector.setSoftMode(true);

describe('tests with first dependency', () => {
  injector.constant('firstDep', firstDep);

  ...

});

describe('tests with second dependency', () => {
  injector.constant('secondDep', secondDep);

  ...
});

...
```

**Comment by jackmellis** [comment]
I will try put something together for this use case.

Out of curiosity, do you not register your dependencies in the setup for all of your tests? i.e.
```js
beforeEach(() => {
  injector.constant('foo', {});
  injector.constant('bah', {});
});

describe('tests with first dependency', () => {
  // ...
});

describe('tests with second dependency', () => {
  // perhaps you now want more than just a stub
  injector.constant('bah', { /* ... */ });
});
```

**Comment by downace** [comment]
Oh, sorry, my example wasn't good. Yes, I'm using global `beforeEach` for this purpose.

Every component has it's own dependencies. IMHO, stubbing all of them in global `beforeEach` looks ugly, stubbing only component's dependencies in every spec takes some time. And we need to not forget adding new dependencies

Doing it in one line of code can save some time for developers. Furthermore, mentioning such option in docs will save some time too, because there will be no need to search for a `beforeEach` solution :)

**Comment by jackmellis** [comment]
Sorry for the delay, this has been fixed in the latest release
