### ISSUE TITLE
Issue with component dependencies and mixin dependencies not merging

### ISSUE THREAD

**Issue by webnoob** [jpex-js/vue-inject#14]
If I have `dependencies: ['someService']` in a mixin then it is included in the component only if that component doesn't declare its own `dependencies: []` field. 

Is this by design? If so, perhaps adding an option so that it merged them would be nice.

My use case would be a global mixin which has a depencies field for my dbService (something I would want access to on each component hence the global mixin but I'd also like each component to be able to specify the dependencies it requires as well.

**EDIT**: It's just occurred to me that this is likely nothing to do with `vue-inject` but vue-loader instead. Does anyone have any experience of this and is what I am trying to do possible?

Seems that someone has asked something similar about the $style: https://github.com/vuejs/vue-loader/issues/835

**Comment by jackmellis** [comment]
So I believe what you want to look into is [optionMergeStrategies](https://vuejs.org/v2/api/#optionMergeStrategies).

I believe the default behaviour is to replace the old with the new, but it should be easy enough to add a `dependencies` property that concatenates the dependencies.

**Comment by webnoob** [comment]
That does indeed look like what I need, many thanks for that. Wasn't aware that option existed.

**Comment by webnoob** [comment]
Simple enough, this does the trick:

```
Vue.config.optionMergeStrategies.dependencies = function (toVal, fromVal) {
  if (!toVal) return fromVal
  if (!fromVal) return toVal
  return toVal.concat(fromVal)
}
```

This assume `dependencies` is always an array which I think is the case so posting here for anyone else who comes across the issue.

**Comment by webnoob** [comment]
Just as a side note, would it be worth adding a comment on the instructions that by default dependencies in mixins will be overridden? It would save people some working out if they encounter the issue like I did (given mixins are a common thing).

**Comment by webnoob** [comment]
Thought I'd post an addendum to my previous code sample as I realise now that vue-inject can support array, string and object in its dependencies declaration. With that in mind, the following can be used to do a proper merge regardless of whether one uses array, another string and another object:

```
Vue.config.optionMergeStrategies.dependencies = function (toVal, fromVal) {
  if (!toVal) return fromVal
  if (!fromVal) return toVal

  function doMerge (obj, src) {
    if (typeof src === 'string') {
      obj[src] = src
    } else {
      for (var key in src) {
        let objectKey = Array.isArray(src) ? src[key] : key
        if (src.hasOwnProperty(key)) obj[objectKey] = src[key]
      }
    }
  }

  let result = {}
  doMerge(result, toVal)
  doMerge(result, fromVal)
  return result
}
```

**Comment by jackmellis** [comment]
Great, thanks. I will probably update the package at some point to do this automatically when you call `Vue.use(vueInject)`

**Comment by webnoob** [comment]
That'd be a nice addition. Thanks for your efforts on this project, it's brill.
