### ISSUE TITLE
Services lazy load

### ISSUE THREAD

**Issue by Focushift** [jpex-js/vue-inject#22]
Hello.

It is possible to define service as async components with webpack?

I mean that i can define service like:

`injector.service('formPrinting', () => import(/* webpackChunkName: "app.services" */ './formPrinting'));`

And promise will be resolved with service only when component created.

**Comment by jackmellis** [comment]
Currently there's no way to lazy-load dependencies. What you have above would inject a promise e.g.

```js
{
  dependencies: [ 'formPrinting' ],
  created() {
    this.formPrinting.then((formPrinting) => {
      ...
    });
  }
}
```
or something similar to that.

Making the injector asynchronous (but still work with synchronous and asynchronous components) would be an absolutely massive overhaul of both this library and its dependencies.
