### ISSUE TITLE
How to use it with `vue-class-component`?

### ISSUE THREAD

**Issue by tom10271** [jpex-js/vue-inject#8]
So I have to create a Decorator for `@dependencies`?

https://github.com/kaorun343/vue-property-decorator/blob/master/src/vue-property-decorator.ts

**Comment by jackmellis** [comment]
I haven't used *vue-property-decorator* or *vue-class-component* (or event *typescript* if I'm honest) but a quick peruse at the documentation would suggest you could get away with something like:
```javascript
@Component({
  dependencies : ['foo', 'bah']
})
```
otherwise, yes you will need to create an `@dependencies` decorator!

**Comment by tom10271** [comment]
I have tried to create my own decorator result in fails.... For the time being I can only in services I need manually....

If anyone have created a decorator which works for Vue Class component and this injector please shares your decorator.

**Comment by tom10271** [comment]
Oh no.... Services injected do not Singleton?

**Comment by jackmellis** [comment]
If I *ever* get the time to look at this I will see if I can create an dependencies decorator. Unless someone more typescript-experienced can knock this out quickly, which would be much appreciated!  
Regarding singleton services: I am looking to make services singletons by default in the next major version, but in the meantime you can call `injector.service(......).lifecycle.application()`
